inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
