inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 18
  Exclude:
    - 'test/**/*_test.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*_test.rb'

Metrics/ModuleLength:
  Max: 150
  Exclude:
    - 'test/**/*_test.rb'

Minitest/MultipleAssertions:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
