service: mfynab
image: davidstosik/mfynab

primary_role: cron
servers:
  cron:
    hosts:
      - 157.180.23.52
    proxy: false

registry:
  server: ghcr.io
  username: davidstosik
  password:
    - GHCR_REGISTRY_PASSWORD
builder:
  arch: amd64

env:
  secret:
    - MONEYFORWARD_USERNAME
    - MONEYFORWARD_PASSWORD
    - YNAB_ACCESS_TOKEN
    - COOKIE_CACHE_PRIME

aliases:
  shell: app exec --interactive --reuse "bash"
